### ISSUE TITLE
dashboard Internal Server Error (500)

### ISSUE THREAD

**Issue by tianhao** [rimusz/coreos-osx-gui-kubernetes-cluster#37]
I am using you app, its great.
It has some issue, I am not modify any thing, just install until finished and open the "Kubernetes UI" by menu, the web show Error below:

```
Internal Server Error (500)
Get https://10.100.0.1:443/api/v1/replicationcontrollers: dial tcp 10.100.0.1:443: getsockopt: connection refused
```

url: http://172.17.15.101:8080/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/#/replicationcontrollers
coreos version: stable

**Comment by jantoniucci** [comment]
I'm facing the same behaviour. Could you please share your solution?

**Comment by rimusz** [comment]
@tianhao have you sorted it out? if you did can you share the solution?

**Comment by tianhao** [comment]
I am not use this app now, I build centos7 vm self, and it's dashboard has the same wrong, because the apiserver-host param was wrong,  I fix my dashboard-controller.yaml file and it work:

```
...
containers:
      - name: kubernetes-dashboard
        image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.0.0
        command:
          - "/dashboard"
          - "--port=9090"
          - "--apiserver-host=192.168.99.100:8080"
...
```

the point is the `apiserver-host` param, it is master host's apiserver ip and port. my cluster not use dns, so set ip and port.

this app idea is great, but I need build system my self and understand it, after that, use this app to improve efficiency, face some issue.

**Comment by rimusz** [comment]
@tianhao thanks for the answer, I will try to update dashboard-controller.yaml file and see what happens

**Comment by JPalmerGithub** [comment]
Internal Server Error (500)
Get https://10.100.0.1:443/api/v1/replicationcontrollers: dial tcp 10.100.0.1:443: getsockopt: connection refused

Same here rimusz

**Comment by JPalmerGithub** [comment]
UPDATE:
Yes, I confirm, the solution from @tianhao WORKS!
I have added the section in the middle into the FILE and issued delete and create commands from iTerm 
that opened by "OS shell" dropdown menu.

FILE: coreos-kubernetes-cluster-osx/src/k8s/dashboard-controller.yaml

```
spec:
  containers:
  - name: kubernetes-dashboard
    image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.0.1
```

```
        command:
          - "/dashboard"
          - "--port=9090"
          - "--apiserver-host=172.17.15.101:8080"
```

```
    resources:
      # keep request = limit to keep this container in guaranteed class
```

kubectl delete -f coreos-kubernetes-cluster-osx/src/k8s/dashboard-controller.yaml
kubectl delete -f coreos-kubernetes-cluster-osx/src/k8s/dashboard-service.yaml
kubectl create -f coreos-kubernetes-cluster-osx/src/k8s/dashboard-controller.yaml
kubectl create -f coreos-kubernetes-cluster-osx/src/k8s/dashboard-service.yaml
